apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
    app.kubernetes.io/part-of: starter-app
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    app: mongodb
